version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: douglasq/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks: 
      - production-networks
    depends_on: 
      - "node1"
      - "node2"
      - "node3"
  
  mongodb:
    image: mongo
    networks:
      - production-networks
  
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books1
    ports:
      - "3000"
    networks: 
      - production-networks
    depends_on: 
      - mongodb
  
  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books2
    ports:
      - "3000"
    networks: 
      - production-networks
    depends_on: 
      - mongodb
  
  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books3
    ports:
      - "3000"
    networks: 
      - production-networks
    depends_on: 
      - mongodb

networks: 
  production-networks:
    driver: bridge
